{
  "response": {
    "version": "0.1",
    "termsofService": "http://www.wunderground.com/weather/api/d/terms.html",
    "features": {
      "conditions": 1
    }
  },
  "current_observation": {
    "image": {
      "url": "http://icons.wxug.com/graphics/wu2/logo_130x80.png",
      "title": "Weather Underground",
      "link": "http://www.wunderground.com"
    },
    "display_location": {
      "full": "Monterey, CA",
      "city": "Monterey",
      "state": "CA",
      "state_name": "California",
      "country": "US",
      "country_iso3166": "US",
      "zip": "93940",
      "magic": "1",
      "wmo": "99999",
      "latitude": "36.59000015",
      "longitude": "-121.87999725",
      "elevation": "14.0"
    },
    "observation_location": {
      "full": "Oak Grove, Monterey CA, Monterey, California",
      "city": "Oak Grove, Monterey CA, Monterey",
      "state": "California",
      "country": "US",
      "country_iso3166": "US",
      "latitude": "36.595032",
      "longitude": "-121.880043",
      "elevation": "60 ft"
    },
    "estimated": {},
    "station_id": "KCAMONTE57",
    "observation_time": "Last Updated on May 4, 7:27 PM PDT",
    "observation_time_rfc822": "Thu, 04 May 2017 19:27:13 -0700",
    "observation_epoch": "1493951233",
    "local_time_rfc822": "Thu, 04 May 2017 19:27:14 -0700",
    "local_epoch": "1493951234",
    "local_tz_short": "PDT",
    "local_tz_long": "America/Los_Angeles",
    "local_tz_offset": "-0700",
    "weather": "Overcast",
    "temperature_string": "53.7 F (12.1 C)",
    "temp_f": 53.7,
    "temp_c": 12.1,
    "relative_humidity": "95%",
    "wind_string": "From the South at 3.3 MPH Gusting to 6.0 MPH",
    "wind_dir": "South",
    "wind_degrees": 180,
    "wind_mph": 3.3,
    "wind_gust_mph": "6.0",
    "wind_kph": 5.3,
    "wind_gust_kph": "9.7",
    "pressure_mb": "1015",
    "pressure_in": "29.97",
    "pressure_trend": "0",
    "dewpoint_string": "52 F (11 C)",
    "dewpoint_f": 52,
    "dewpoint_c": 11,
    "heat_index_string": "NA",
    "heat_index_f": "NA",
    "heat_index_c": "NA",
    "windchill_string": "NA",
    "windchill_f": "NA",
    "windchill_c": "NA",
    "feelslike_string": "53.7 F (12.1 C)",
    "feelslike_f": "53.7",
    "feelslike_c": "12.1",
    "visibility_mi": "9.0",
    "visibility_km": "14.5",
    "solarradiation": "--",
    "UV": "0",
    "precip_1hr_string": "0.00 in ( 0 mm)",
    "precip_1hr_in": "0.00",
    "precip_1hr_metric": " 0",
    "precip_today_string": "0.00 in (0 mm)",
    "precip_today_in": "0.00",
    "precip_today_metric": "0",
    "icon": "cloudy",
    "icon_url": "http://icons.wxug.com/i/c/k/cloudy.gif",
    "forecast_url": "http://www.wunderground.com/US/CA/Monterey.html",
    "history_url": "http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCAMONTE57",
    "ob_url": "http://www.wunderground.com/cgi-bin/findweather/getForecast?query=36.595032,-121.880043",
    "nowcast": ""
  }
}